# @package _global_

# 300M Param.

transformer_lm:
  dim: 1024
  num_heads: 16
  num_layers: 24

beatmapgen_lm:
  transfer_dim: 64
  transfer_num_heads: 8
  transfer_num_layers: 2

representation_model: /root/autodl-tmp/audiocraft_download/beatmapgen_finetune_musicgen-small.th